### PR TITLE
Add illumos support 

### LINKED ISSUE #10: support for illumos
This package is currently blocking building lapce/lapce on illumos. This issue is to track fixing this issue

### PR DESCRIPTION
**Pull request by Toasterson**
fixes #10

### CODE REVIEW

**Comment by wesleywiser** [comment]
Thanks for the PR! Would you also mind updating the ["Supported Platforms"](https://github.com/wesleywiser/process_path#supported-platforms) table in the readme?

**Comment by Toasterson** [comment]
@wesleywiser Oh, absolutely. Sorry though it was automatically updated from the code.

**Comment by Toasterson** [comment]
Done

**Review by wesleywiser — APPROVED** [review]

**Comment by wesleywiser** [comment]
No worries @Toasterson, thanks so much for the fix! 🙂

**Pull request merged**
